version: '3.9'

services:
  server:
    build: ./server
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
    volumes:
      - ./server:/app
    restart: unless-stopped

  client:
    build: ./client
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - ./client:/app
    depends_on:
      - server
    restart: unless-stopped
